name: ci.yml

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn run lint
      - run: yarn format --check
      - name: Build
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && github.repository == 'cliclitv/pwa'
        run: yarn build
      - name: Deploy
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && github.repository == 'cliclitv/pwa'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
